Merged in JDCMT-200-automate-upload-to-mpac-process (pull request #28)
JDCMT-200 automate upload to mpac process

* JDCMT-200 upload artifacts to MAPC using API

* JDCMT-200 remove copying of the artifact

* JDCMT-200 upload artifacts first then publish new version

* JDCMT-200 set proper credentials

* JDCMT-200 added echo for debugging

* JDCMT-200 extract .zip artifact (MPAC doesn't allows .zip)

* JDCMT-200 change file path to the artifact

* JDCMT-200 fixed wrong variable name

* JDCMT-200 fixed artifact_url typo

* JDCMT-200 added sleep after artifact upload

* JDCMT-200 match artifact version

* JDCMT-200 adjust build number generation


Approved-by: Marek Parfianowicz
Approved-by: Volodymyr Batrukh

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -60,14 +60,14 @@ definitions:
         artifacts:
           - RefAppAddon.*.zip
     - step: &buildAndTest
-          name: Build & test
-          image:
-            name: docker-proxy.services.atlassian.com/atlassian/netrunners/ubuntu-pwsh-mvn
-            username: netrunners
-            password: $PIPELINES_JWT_TOKEN
-          script:
-            # Build package and run tests
-            - atlas-mvn test
+        name: Build & test
+        image:
+          name: docker-proxy.services.atlassian.com/atlassian/netrunners/ubuntu-pwsh-mvn
+          username: netrunners
+          password: $PIPELINES_JWT_TOKEN
+        script:
+          # Build package and run tests
+          - atlas-mvn test
     - step: &createTag
         name: Create tag
         script:
@@ -111,9 +111,81 @@ definitions:
             ENCODED_BRANCH=$(echo "$BITBUCKET_BRANCH" | jq -sRr @uri)
             STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonar-enterprise.internal.atlassian.com/api/qualitygates/project_status?projectKey=msteams-jira-onprem-addon&branch=$ENCODED_BRANCH" | jq -r .projectStatus.status)
             if [ "$STATUS" != "OK" ]; then
-               echo "Quality gate failed: https://sonar-enterprise.internal.atlassian.com/dashboard?branch=$ENCODED_BRANCH&id=msteams-jira-onprem-addon"
+               echo "Quality gate failed: https://sonar-enterprise.internal.atlassian.com/dashboard?id=msteams-jira-onprem-addon&branch=$ENCODED_BRANCH"
                exit 1
             fi
+    - step: &uploadToMarketplace
+        name: Upload new version to Marketplace
+        image:
+          name: docker-proxy.services.atlassian.com/atlassian/netrunners/ubuntu-pwsh-mvn
+          username: netrunners
+          password: $PIPELINES_JWT_TOKEN
+        script:
+          - VERSION=$(echo "$BITBUCKET_BRANCH" | sed 's/release\///')
+          - artifactZipFileName="RefAppAddon.Production.$VERSION.zip"
+          - mkdir artifacts
+          - unzip -q "$artifactZipFileName" -d ./artifacts
+          - artifactFileName="./artifacts/$(ls ./artifacts)"
+          - echo $artifactFileName
+          - credentials="${MPAC_BOT_LOGIN}:${MPAC_BOT_TOKEN}"
+          # Upload artifact to Marketplace
+          - |
+            response=$(curl --request POST \
+             --url https://marketplace.atlassian.com/rest/2/assets/artifact \
+             --user "$credentials" \
+             --header 'Accept: application/json' \
+             --header 'Content-Type: multipart/form-data' \
+             --form file=@"$artifactFileName")
+          - echo $response
+          - artifact_url=$(echo "$response" | jq -r '._links.binary.href')
+          - |
+            # Check if the extraction was successful
+            if [ -n "$artifact_url" ]; then
+                echo "Artifact URL: $artifact_url"
+            else
+                echo "Failed to extract Artifact URL from the response."
+                exit 1
+            fi
+          - sleep 60
+          - buildName=$(echo "$BITBUCKET_BRANCH" | sed 's/release\///')
+          - buildNumber=$(echo "$VERSION" | tr -d '.')00
+          - |
+            curl --request POST \
+                 --url 'https://marketplace.atlassian.com/rest/2/addons/microsoft-teams/versions' \
+                 --user ${credentials} \
+                 --header 'Content-Type: application/json' \
+                 --data '{
+                   "_links": {
+                     "self": {
+                       "href": "/rest/2/addons/microsoft-teams/versions/build/'${buildNumber}'"
+                     },
+                   "artifact": {
+                       "href": "'${artifact_url}'"
+                   }},
+                   "buildNumber": '${buildNumber}',
+                   "name": "'${buildName}'",
+                   "status": "private",
+                   "compatibilities": [
+                     {
+                       "application": "jira",
+                       "hosting": {
+                         "dataCenter": {
+                           "min": {
+                               "build": 900003
+                           },
+                           "max": {
+                               "build": 9170000
+                           }}
+                       }
+                     }
+                   ],
+                   "vendorLinks": {
+                     "documentation": "https://www.msteams-atlassian.com/JiraServer/",
+                     "license": "https://www.atlassian.com/licensing/marketplace/termsofuse",
+                     "eula": "https://www.atlassian.com/licensing/marketplace/termsofuse",
+                     "learnMore": "https://www.msteams-atlassian.com/JiraServer/"
+                   }
+                 }'
 pipelines:
   default:
     - step:
@@ -163,6 +235,10 @@ pipelines:
           <<: *buildAndPack
           name: Build production package
           deployment: Production
+      - step:
+          <<: *uploadToMarketplace
+          name: Upload packages to Atlassian Marketplace
+          trigger: manual
       - step:
           <<: *createTag
           trigger: manual
