Merged in JSMT-201-setup-sonarqube-quality-gate (pull request #22)
JSMT-201 fail build if quality gate failed

* JSMT-201 fail build if quality gate failed

* JSMT-201 code smell to test quality gate

* JSMT-201 install jq

* JSMT-201 remove code smell to test quality gate

* JSMT-201 update docker image to install jq

* JSMT-201 encode BITBUCKET_BRANCH variable


Approved-by: Volodymyr Batrukh

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -103,6 +103,13 @@ definitions:
           password: $PIPELINES_JWT_TOKEN
         script:
           - atlas-mvn verify sonar:sonar -Dsonar.projectKey=msteams-jira-onprem-addon -Pcoverage
+          - |
+            ENCODED_BRANCH=$(echo "$BITBUCKET_BRANCH" | jq -sRr @uri)
+            STATUS=$(curl -s -u $SONAR_TOKEN: "https://sonar-enterprise.internal.atlassian.com/api/qualitygates/project_status?projectKey=msteams-jira-onprem-addon&branch=$ENCODED_BRANCH" | jq -r .projectStatus.status)
+            if [ "$STATUS" != "OK" ]; then
+               echo "Quality gate failed: https://sonar-enterprise.internal.atlassian.com/dashboard?branch=$ENCODED_BRANCH&id=msteams-jira-onprem-addon"
+               exit 1
+            fi
 pipelines:
   default:
     - step:
